
# local dev testing of production build
services:
  app:
    container_name: alkime-memos-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HUGO_BASEURL=http://localhost:8080/
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=debug
      - ENV=production
      - GIN_MODE=release
    restart: unless-stopped
